### ISSUE TITLE
Empty star rating not displayed

### ISSUE THREAD

**Issue by ankitaraikundalia** [ThemeFuse/Unyson-Feedback-Extension#4]
Hi,
I have a custom post type for courses. I have enabled feedback for it from back-end. However, I don't see the empty stars on all courses on the archive page. Star ratings are displayed only if at-least one review is given on that course.
How can I display empty stars for all courses where no reviews are been provided yet?

Below is the screenshot for making my question more clear:
![index](https://cloud.githubusercontent.com/assets/9928664/6591782/d505d3c2-c7ea-11e4-8d14-b3d2d0816c64.png)

**Comment by valeriuzdrobau** [comment]
You can control this from in file: `framework-customizations\extensions\feedback\extensions\feedback-stars\views\view-rates.php`

**Comment by ankitaraikundalia** [comment]
@valeriuzdrobau - Thank You..
