### ISSUE TITLE
How can I disable extension for my theme?

### ISSUE THREAD

**Issue by blackyangell** [ThemeFuse/Unyson-Feedback-Extension#5]
Hi. I'd like to disable Feedback extension completely for my theme. 
I need to do it not by 'Activate/Deactivate' buttons on 'Unyson Extensions' dashboard, because when somebody will install my theme, Feedback must be automatically disabled.

For shortcodes, for example, I can use this code to disable some of them:

function _filter_theme_disable_default_shortcodes($to_disable) {
    $to_disable[] = 'slider';
    $to_disable[] = 'call_to_action';
    $to_disable[] = 'notification';
    $to_disable[] = 'widget_area';
    return $to_disable;
}
add_filter('fw_ext_shortcodes_disable_shortcodes', '_filter_theme_disable_default_shortcodes');

Can I put some code to disable Feedback?
Will be very appreciate for help.

**Comment by moldcraft** [comment]
Hello,

You can't disable extensions. If you really want to hide it completely, you can do it from css (find its id in html).

At the moment, you can set extensions that your theme support in `$manifest['supported_extensions']` http://manual.unyson.io/en/latest/manifest/theme.html#content Not compatible extensions will be hidden by the **Show/Hide Other Extensions** button

**Comment by blackyangell** [comment]
The problem is that this extension change my default comments.php template for single.php. 
I have modified comments.php file, it works on pages, custom post types, but it doesn't work on single.php when Feedback extension is enabled (as you guess, CSS can't help here).

I guess this function does all magic:

public function _action_add_feedback_support(){
	$post_types = fw_get_db_ext_settings_option( 'feedback', 'post_types', array('post' => true) );
	foreach ( $post_types as $slug => $value ) {
		add_post_type_support( $slug, 'comments' );
		add_post_type_support( $slug, $this->supports_feature_name );
	}
}

Maybe I can remove post type support of Feedback extension for 'post' type?

**Comment by moldcraft** [comment]
> as you guess, CSS can't help here

I mean to include a css in Unyson Extensions page, and to hide the Feedback extension from the list

**Comment by blackyangell** [comment]
I understand what do you mean, I did it already. But when I hide it, extension continues to work, and I can get my comments.php file on single page... That is the main problem.

**Comment by moldcraft** [comment]
How the user will install it if it's hidden?

**Comment by blackyangell** [comment]
This extension is not installed and enabled by default?

**Comment by moldcraft** [comment]
No.

There are 2 ways to install extensions:

* By clicking on Install
* After Unyson plugin is activated the user will be redirected to a page to install compatible extensions, the ones you specified in $manifest['supported_extensions'].

So do not put `'feedback' => array()` in manifest and the user will have no possibility to install it.

**Comment by blackyangell** [comment]
Ok, thank you very much, I will follow your advice!
