### ISSUE TITLE
How I can get one feedback with showing rating?

### ISSUE THREAD

**Issue by anndy33** [ThemeFuse/Unyson-Feedback-Extension#6]
I had a problem when worked with feedback extension, I want to get one feedback of current post with rating, but I can't show rating of this feedback. Can you give me solution for this situation?

**Comment by ViorelEremia** [comment]
I do not understand what do you want to do. You want to get a feedback for a comment `get_comment_meta( $comment->comment_ID,'fw-feedback-stars', true )`, or you want to calculate a total rating for this post

**Comment by anndy33** [comment]
My problem is that I want to get only one feedback in total feedback of current post, it can be like that: 
![capture](https://user-images.githubusercontent.com/11587691/32366978-077d0672-c0b3-11e7-99d9-d36087c1080a.PNG)
But currently, I can not get and show star for rating.  I just get some information like below:
![capture2](https://user-images.githubusercontent.com/11587691/32367014-28e4a568-c0b3-11e7-9aee-343fe7cfe683.PNG)
So, you can give me the solution to show star for rating of this post?
Thankyou!

**Comment by dylan-ngo11** [comment]
I think you can use the function above to get the rate then use the foreach() to print the star.

**Comment by ViorelEremia** [comment]
Ok if I understand correctly to get rading for one comment you need to know comment ID: `get_comment_meta( $comment->comment_ID,'fw-feedback-stars', true )`.
If you have custom loop of posts and you want to get one feedeback: 
`while(have_post bla bla) {
      // Here is availble global post id just extract comments with raiting 2.
      foreach ( get_comments( array( 'meta_key' => 'fw-feedback-stars', 'meta_value' => 2 ) ) as $comment ) {
	// Stars always are 2
     }
}`
Or you want to extract the biggest raiting feedback for a post? 
` 
$max_rating = fw_get_db_ext_settings_option( 'feedback', 'feedback_stars_stars_number', 5 );
			$commentIdWithTheBestFeedback = '';
			$bestRaiting = 0;

			foreach ( get_comments() as $comment ) {
				$raiting = get_comment_meta( $comment->comment_ID, 'fw-feedback-stars', true );

				if ( ! $raiting ) {
					continue;
				}

				if ( $raiting == $max_rating ) {
					$bestRaiting = $raiting;
					$commentIdWithTheBestFeedback = $comment->comment_ID;
					break;
				}

				if ( $raiting > $bestRaiting ) {
				    $bestRaiting = $raiting;
				    $commentIdWithTheBestFeedback = $comment->comment_ID;
                }

			}

            // show feedback if raiting is 4 or higher
			if ( $bestRaiting >= 4 ) {
			    $comment = get_comment( $commentIdWithTheBestFeedback );
				//$raiting = get_comment_meta( $comment->comment_ID, 'fw-feedback-stars', true );
                //do stuff here message avatar etc.
            }
`
Or in your purchased theme does not work raitings.

**Comment by anndy33** [comment]
yep, I can do it, it worked. Thank you!

**Comment by JohanvdS** [comment]
I have  a problem the rate option is gone. Feedback is working but not with this rating issue see [https://tvnr.be](https://tvnr.be) Now i have to put it manually from friends [https://tvnr.be/feedback-en-reacties/](https://tvnr.be/feedback-en-reacties) you can fil in everything but missing star rating :( is there something i can resolve I am new and know a little about scripts :(
